name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to v3 for Node.js 20 support

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: Rezazare76 # Hardcoded username to avoid undefined issue

      - name: Create output directory
        run: mkdir -p dist

      - name: Move snake.svg to dist
        run: mv snake.svg dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE }}
